Draft: Small spack changes to cleanup spack process on HPC Clusters
pnnl/ExaGO pull request #133
Opened 2024-03-29 15:13 UTC by cameronrutherford

**Merge request type**
- [x] Resolves bug

**Relates to**
- [x] Spack configuration

**This MR updates**
- [x] Spack configuration

**Summary**

No specific issue being addressed here, just some quality of life changes to some of our spack scripts. This makes it so that the spack environment is created in a single line, and that there is no longer a `module purge` that is ran before config is loaded. This is helpful to prevent harmful environment modifications by our scripts where they might be unnecessary.

If these changes are ok, we can extend this to other clusters as needed. Many of the whitespace changes were automatically made by my editor, and we can change / revert as needed. We don't really have any bash linting configuration or developer guidelines surrounding those files...

2024-03-29 15:15 UTC, cameronrutherford commented on buildsystem/spack/load_spack.sh
> +	spack env create -d $SPACKENV $base/spack.yaml &&
This is the main change.... No longer are we running `spack env create` before a `cp` command, we just do it all in one line using spack native commands.

2024-04-23 18:43 UTC, cameronrutherford commented
@jaelynlitz please review I think this is good to merge

2024-04-23 19:03 UTC, jaelynlitz requested changes
Generally looks good, just some small changes requested 😄

2024-04-23 19:03 UTC, jaelynlitz commented on buildsystem/spack/deception/env.sh
> +# Just for CI
Can you extend these changes to newell and incline too 😄

2024-04-23 19:03 UTC, jaelynlitz commented on buildsystem/spack/deception/env.sh
>  module load openmpi/4.1.0mlx5.0
Maybe add a `module list` for sanity checks?

2024-04-23 19:03 UTC, jaelynlitz commented on buildsystem/spack/deception/env.sh
> +source /share/apps/python/miniconda3.9/etc/profile.d/conda.sh >/dev/null 2>&1
Thank you for removing this output

2024-05-09 18:44 UTC, cameronrutherford commented
@jaelynlitz please re-review

2024-05-22 23:47 UTC, jaelynlitz approved these changes

2024-05-23 18:03 UTC, merged