Use #if defined instead of #if and turn off -Werror for debug builds
pnnl/ExaGO pull request #68
Opened 2023-11-09 00:03 UTC by abhyshr

`#if` does not work correctly on Mac so switching to `#if defined`. Noticed this behavior for
`#if (EXAGO_ENABLE_IPOPT || EXAGO_ENABLE_HIOP)` so replaced it with
`#if  defined EXAGO_ENABLE_IPOPT || defined EXAGO_ENABLE_HIOP`.

Also removed the `-Werror` flag for debug builds. `sprintf` is depecreated for clang and so `-Werror` flag results in zillions of errors. Note that the error is thrown not only for `sprintf` in ExaGO code, but also if it is any dependency library. Need to tackle this through a separate issue so turning off the `-Werror` for now.

2023-11-20 03:44 UTC, cameronrutherford commented on src/utils/CMakeLists.txt
> +    "$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CONFIG:DEBUG>>:-Wall;-Wextra;-Wpedantic>"
Turns out it's really easy to add platform specific CMake in cases like this. https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Write-Platform-Checks#platform-variables

You can just do:

```CMake
if(APPLE)

endif()
```

2023-11-20 03:46 UTC, cameronrutherford requested changes
I was struggling to add the suggested changes in the GitHub IDE, but let's add the MacOS stuff into a conditional, and set everything else to the current setting.

2023-11-20 03:46 UTC, cameronrutherford commented
Also this is a +1 for #52

2023-11-20 20:49 UTC, cameronrutherford commented
I will PR into this with CMake suggestion. Still not sure why tests are failing on Newell + Ascent. Noteably two different tests are failing.

2023-11-20 20:56 UTC, cameronrutherford approved these changes

2023-11-20 20:57 UTC, cameronrutherford approved these changes, later dismissed

2023-11-20 21:04 UTC, bjpalmer approved these changes, later dismissed

2023-11-20 22:23 UTC, cameronrutherford commented
Newell and Ascent are still failing so if someone can take a look into those failures then I am happy to merge

2023-11-21 14:38 UTC, wperkins commented on src/utils/CMakeLists.txt
Should there be some testing of the compiler here?  What compiler is assumed here, Apple CLang? Does the same thing happen w/ GNU.  I guess I'm asking is this a (host) compiler, (gpu) compiler, or system issue?  And, I only ask this because I don't like the Apple CLang compiler.

2023-11-21 16:16 UTC, cameronrutherford commented on src/utils/CMakeLists.txt
That's a good question. @abhyshr should we just be doing this with apple clang, or all Apple devices?

2023-11-21 16:19 UTC, cameronrutherford commented
Since this seems to have gotten lost in the comments - tests are failing on Newell and Ascent. Please fix

2023-11-21 16:34 UTC, abhyshr commented on src/utils/CMakeLists.txt
I've seen this on my Mac using Clang. Not tested with any other compiler. The issue is that #if does not work with Clang so one needs to use #if defined instead. This is a fix that I thought would work, but maybe it is not (?). What are the other solutions?

2023-11-21 16:38 UTC, abhyshr commented on src/utils/CMakeLists.txt
Looking at the PETSc code, I see that it use `#if defined` convention. Since PETSc has builds across many more platforms than we do, I think using `#if defined` would be better than just `#if`

2023-11-21 16:42 UTC, wperkins commented on src/utils/CMakeLists.txt
Sorry, I should have been more specific. I was commenting on abandoning  `-Werror` on `APPLE` regardless of the compiler used. Fixing `#if` behavior is fine w/ me.

2023-11-21 18:19 UTC, cameronrutherford commented on src/utils/CMakeLists.txt
It's relatively easy to limit the compiler flag based on only Apple Clang, and it sounds like that's what we should be doing?

I can create a PR for this if that's the consensus

2023-11-22 03:44 UTC, abhyshr commented on src/utils/CMakeLists.txt
Without the `-Werror` stuff, is this PR good to be merged?

2023-11-22 03:58 UTC, cameronrutherford commented on src/utils/CMakeLists.txt
Tests are failing on Newell and Ascent, so no

2023-11-22 03:58 UTC, cameronrutherford commented
> Since this seems to have gotten lost in the comments - tests are failing on Newell and Ascent. Please fix

@abhyshr

2023-11-22 13:46 UTC, wperkins commented on src/utils/CMakeLists.txt
> It's relatively easy to limit the compiler flag based on only Apple Clang, and it sounds like that's what we should be doing?
> 
> I can create a PR for this if that's the consensus

I would vote for this.

2023-11-22 14:17 UTC, cameronrutherford commented on src/utils/CMakeLists.txt
Happy to add the apple clang conditional, but we still have test failures

2023-11-28 19:01 UTC, bjpalmer commented
I just ran this branch on deception and tests 20 and 21 are passing. These were the ones that you were reporting as failing, correct? I'm only seeing failures for 17,18,19.

2023-11-29 03:11 UTC, cameronrutherford commented
> I just ran this branch on deception and tests 20 and 21 are passing. These were the ones that you were reporting as failing, correct? I'm only seeing failures for 17,18,19.

Remember we still are skipping some tests in CI per #43 and #3, which @jaelynlitz is also helping resolve. I think 17,18,19 are all skipped, and so you should see Deception tests passing as is reflected in PR status.

You will only see test failures on Ascent and Newell, as is reflected in GitHub commit status.

2023-11-29 05:03 UTC, cameronrutherford approved these changes

2023-11-29 05:05 UTC, merged